spring.application.name=code

spring.datasource.url=jdbc:mysql://https://labs-mysql-fast-hot-electrician.mysql.databases.labs.skills.network/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=Qx9iCpHvhQwkNraxxf6Jdf4m
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:s44yA9YuMOmSdR8JEMTKte9e@172.21.46.247:27017/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 

